openapi: 3.0.0
info:
  version: '1.0'
  title: User API
  description: API destinated to user management

paths:
  /users/{id}:
    get:
      tags:
          - Users
      summary: Get an user by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '415':
          description: Unsuported media type error
        '409':
          description: Conflict error
        '403':
          description: Forbidden error
        '400':
          description: Bad Request error
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UsersFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
    patch:
      tags:
            - Users
      summary: Update an user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '415':
          description: Unsuported media type error
        '409':
          description: Conflict error
        '403':
          description: Forbidden error
        '400':
          description: Bad Request error
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UsersFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
    delete:
      tags:
          - Users
      summary: Delete an user
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '415':
          description: Unsuported media type error
        '409':
          description: Conflict error
        '403':
          description: Forbidden error
        '400':
          description: Bad Request error
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UsersFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
  /users/{id}/relationships/{relation}:
    get:
      tags:
          - Users
      summary: Get all relation registers of a specific user
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
        - in: path
          name: relation
          required: true
          schema:
            type: string
            enum:
              - orders
      responses:
        '200':
          description: Successful response
        '415':
          description: Unsuported media type error
        '409':
          description: Conflict error
        '403':
          description: Forbidden error
        '400':
          description: Bad Request error
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UsersFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
  /users/{id}/{relation}:
    get:
      tags:
          - Users
      summary: Get all relation registers of a specific user
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
        - in: path
          name: relation
          required: true
          schema:
            type: string
            enum:
              - orders
      responses:
        '200':
          description: Successful response
        '415':
          description: Unsuported media type error
        '409':
          description: Conflict error
        '403':
          description: Forbidden error
        '400':
          description: Bad Request error
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UsersFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
  /users:
    post:
      tags:
          - Users
      summary: Create an user
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/User'
            example:
              data:
                type: people
                attributes:
                  name: John Doe
                  email: johndoe@email.com
                  isEmployee: false
      responses:
        '201':
          description: Successful response
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Example:
                  value:
                    data:
                      type: people
                      id: some-id
                      attributes:
                        name: John Doe
                        email: johndoe@email.com
                        isEmployee: false
        '415':
          description: Unsuported media type error
        '409':
          description: Conflict error
        '403':
          description: Forbidden error
        '400':
          description: Bad Request error
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UsersFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
    get:
      tags:
          - Users
      summary: Get all users
      responses:
        '200':
          description: Successful response
        '415':
          description: Unsuported media type error
        '409':
          description: Conflict error
        '403':
          description: Forbidden error
        '400':
          description: Bad Request error
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UsersFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        isEmployee:
          type: boolean
        orders:
          type: array
          items:
            $ref: '#/components/schemas/Order'
      required:
        - id
        - name
        - email
        - isEmployee
    Order:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        totalPrice:
          type: number
        orderDate:
          type: string
        orderItems:
          type: array
          items:
            $ref: '#/components/schemas/OrderItems'
      required:
        - id
        - userId
        - totalPrice
        - orderItems
    OrderItems:
      type: object
      properties:
        id:
          type: string
        snackId:
          type: string
        ingredientId:
          type: string
        itemAmount:
          type: integer
      required:
        - id
        - snackId
        - ingredientId
        - itemAmount
