openapi: 3.0.0
info:
  version: '1.0'
  title: Ingredient API
  description: API destinated to ingredient management

paths:
  /ingredients/{id}:
    get:
      tags:
          - Ingredients
      summary: Get an ingredient by ID
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            enum:
              - application/vnd.api+json
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '415':
          description: Unsuported media type error
        '409':
          description: Conflict error
        '403':
          description: Forbidden error
        '400':
          description: Bad Request error
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UsersFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
    patch:
      tags:
            - Ingredients
      summary: Update an ingredient
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/Ingredient'
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '415':
          description: Unsuported media type error
        '409':
          description: Conflict error
        '403':
          description: Forbidden error
        '400':
          description: Bad Request error
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UsersFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
    delete:
      tags:
          - Ingredients
      summary: Delete an ingredient
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            enum:
              - application/vnd.api+json
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '415':
          description: Unsuported media type error
        '409':
          description: Conflict error
        '403':
          description: Forbidden error
        '400':
          description: Bad Request error
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UsersFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
  /ingredients/{id}/relationships/{relation}:
    get:
      tags:
          - Ingredients
      summary: Get all relation registers of a specific ingredient
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            enum:
              - application/vnd.api+json
        - in: path
          name: id
          required: true
          schema:
            type: string
        - in: path
          name: relation
          required: true
          schema:
            type: string
            enum:
              - snacks
              - menus
              - orders
      responses:
        '200':
          description: Successful response
        '415':
          description: Unsuported media type error
        '409':
          description: Conflict error
        '403':
          description: Forbidden error
        '400':
          description: Bad Request error
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UsersFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
  /ingredients/{id}/{relation}:
    get:
      tags:
          - Ingredients
      summary: Get all relation registers of a specific ingredient
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            enum:
              - application/vnd.api+json
        - in: path
          name: id
          required: true
          schema:
            type: string
        - in: path
          name: relation
          required: true
          schema:
            type: string
            enum:
              - snacks
              - menus
              - orders
      responses:
        '200':
          description: Successful response
        '415':
          description: Unsuported media type error
        '409':
          description: Conflict error
        '403':
          description: Forbidden error
        '400':
          description: Bad Request error
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UsersFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
  /ingredients:
    post:
      tags:
          - Ingredients
      summary: Create an ingredient
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/Ingredient'
            example:
              data:
                type: ingredient
                attributes:
                  name: Pão
                  unitMoneyAmount: 4
                  availableAmount: 15
      responses:
        '201':
          description: Successful response
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Ingredient'
              examples:
                Example:
                  value:
                    data:
                      type: ingredient
                      id: some-id
                      attributes:
                        name: Pão
                        unitMoneyAmount: 4
                        availableAmount: 15
        '415':
          description: Unsuported media type error
        '409':
          description: Conflict error
        '403':
          description: Forbidden error
        '400':
          description: Bad Request error
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UsersFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
    get:
      tags:
          - Ingredients
      summary: Get all ingredients
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            enum:
              - application/vnd.api+json
      responses:
        '200':
          description: Successful response
        '415':
          description: Unsuported media type error
        '409':
          description: Conflict error
        '403':
          description: Forbidden error
        '400':
          description: Bad Request error
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UsersFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy

components:
  schemas:
    Ingredient:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        unitMoneyAmount:
          type: number
        availableAmount:
          type: integer
