swagger: '2.0'
info:
  version: '1.0'
  title: Menu API
  description: Teste de API
paths:
  /menus/{id}:
    get:
      summary: Get a menu by ID
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: Successful response
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MenusFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
    put:
      summary: Update a menu
      parameters:
        - in: path
          name: id
          required: true
          type: string
        - in: body
          name: menu
          required: true
          schema:
            $ref: '#/definitions/Menu'
      responses:
        '200':
          description: Successful response
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MenusFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
    delete:
      summary: Delete a menu
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: Successful response
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MenusFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
  /menus/{id}/relationships/{relation}:
    get:
      summary: Get all relation registers from a menu
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: Successful response
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MenusFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
  /menus/{id}/{relation}:
    get:
      summary: Get all relation registers from a menu
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: Successful response
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MenusFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
  /menus:
    post:
      summary: Create a menu
      parameters:
        - in: body
          name: menu
          required: true
          schema:
            $ref: '#/definitions/Menu'
      responses:
        '201':
          description: Successful response
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MenusFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
    get:
      summary: Get all menus
      responses:
        '200':
          description: Successful response
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MenusFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
definitions:
  Menu:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
