openapi: 3.0.0
info:
  version: '1.0'
  title: Menu API
  description: API destinated to menu management

paths:
  /menus/{id}:
    get:
      tags:
          - Menus
      summary: Get a menu by ID
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            enum:
              - application/vnd.api+json
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '415':
          description: Unsuported media type error
        '409':
          description: Conflict error
        '403':
          description: Forbidden error
        '400':
          description: Bad Request error
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UsersFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
    patch:
      tags:
            - Menus
      summary: Update a menu
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/Menu'
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '415':
          description: Unsuported media type error
        '409':
          description: Conflict error
        '403':
          description: Forbidden error
        '400':
          description: Bad Request error
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UsersFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
    delete:
      tags:
          - Menus
      summary: Delete a menu
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            enum:
              - application/vnd.api+json
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '415':
          description: Unsuported media type error
        '409':
          description: Conflict error
        '403':
          description: Forbidden error
        '400':
          description: Bad Request error
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UsersFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
  /menus/{id}/relationships/{relation}:
    get:
      tags:
          - Menus
      summary: Get all relation registers of a specific menu
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            enum:
              - application/vnd.api+json
        - in: path
          name: id
          required: true
          schema:
            type: string
        - in: path
          name: relation
          required: true
          schema:
            type: string
            enum:
              - ingredients
              - snacks
      responses:
        '200':
          description: Successful response
        '415':
          description: Unsuported media type error
        '409':
          description: Conflict error
        '403':
          description: Forbidden error
        '400':
          description: Bad Request error
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UsersFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
  /menus/{id}/{relation}:
    get:
      tags:
          - Menus
      summary: Get all relation registers of a specific menu
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            enum:
              - application/vnd.api+json
        - in: path
          name: id
          required: true
          schema:
            type: string
        - in: path
          name: relation
          required: true
          schema:
            type: string
            enum:
              - ingredients
              - snacks
      responses:
        '200':
          description: Successful response
        '415':
          description: Unsuported media type error
        '409':
          description: Conflict error
        '403':
          description: Forbidden error
        '400':
          description: Bad Request error
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UsersFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
  /menus:
    post:
      tags:
          - Menus
      summary: Create a menu
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/Menu'
            example:
              data:
                type: menu
                attributes:
                  name: Vegetariano
                  description: Pratos saudáveis, pensando nos animais.
                  menuItems:
                    - snackId: null
                      ingredientId: some-ingredient-id
                    - snackId: some-snack-id
                      ingredientId: null
      responses:
        '201':
          description: Successful response
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Menu'
              examples:
                Example:
                  value:
                    data:
                      type: menu
                      id: some-id
                      attributes:
                        name: Vegetariano
                        description: Pratos saudáveis, pensando nos animais.
                        menuItems:
                          - id: some-id
                            snackId: null
                            ingredientId: some-ingredient-id
                          - id: some-id-2
                            snackId: some-snack-id
                            ingredientId: null
                          
        '415':
          description: Unsuported media type error
        '409':
          description: Conflict error
        '403':
          description: Forbidden error
        '400':
          description: Bad Request error
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UsersFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
    get:
      tags:
          - Menus
      summary: Get all menus
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            enum:
              - application/vnd.api+json
      responses:
        '200':
          description: Successful response
        '415':
          description: Unsuported media type error
        '409':
          description: Conflict error
        '403':
          description: Forbidden error
        '400':
          description: Bad Request error
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UsersFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy

components:
  schemas:
    Menu:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        menuItems:
          type: array
          items:
            $ref: '#/components/schemas/MenuItems'
      required:
        - id
        - name
        - description
        - unitMoneyAmount
        - snackItems
    MenuItems:
      type: object
      properties:
        id:
          type: string
        snackId:
          type: string
        ingredientId:
          type: string
      required:
        - id
        - snackId
        - ingredientId

