swagger: '2.0'
info:
  version: '1.0'
  title: Snack API
  description: Teste de API
paths:
  /snacks/{id}:
    get:
      summary: Get a snack by ID
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: Successful response
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SnacksFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
    put:
      summary: Update a snack
      parameters:
        - in: path
          name: id
          required: true
          type: string
        - in: body
          name: snack
          required: true
          schema:
            $ref: '#/definitions/Snack'
      responses:
        '200':
          description: Successful response
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SnacksFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
    delete:
      summary: Delete a snack
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: Successful response
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SnacksFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
  /snacks/{id}/relationships/{relation}:
    get:
      summary: Get all relation registers from a snack
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: Successful response
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SnacksFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
  /snacks/{id}/{relation}:
    get:
      summary: Get all relation registers from a snack
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: Successful response
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SnacksFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
  /snacks:
    post:
      summary: Create a snack
      parameters:
        - in: body
          name: snack
          required: true
          schema:
            $ref: '#/definitions/Snack'
      responses:
        '201':
          description: Successful response
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SnacksFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
    get:
      summary: Get all snacks
      responses:
        '200':
          description: Successful response
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SnacksFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
definitions:
  Snack:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      unitMoneyAmount:
        type: number
